// tianciyinji-admin-backend-master/pages/categories.vue
<template>
  <div>
    <div class="page-header">
      <h2>分类管理</h2>
      <a-button type="primary" @click="openCreate">新建分类</a-button>
    </div>

    <a-table
      :dataSource="categories"
      :columns="columns"
      :loading="loading"
      :pagination="false"
      rowKey="id"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'actions'">
          <a-space>
            <a-button type="link" @click="openEdit(record)">编辑</a-button>
            <a-popconfirm
              title="确定删除该分类？"
              ok-text="是"
              cancel-text="否"
              @confirm="() => handleDelete(record.id)"
            >
              <a-button type="link" danger>删除</a-button>
            </a-popconfirm>
          </a-space>
        </template>
      </template>
    </a-table>

    <a-modal
      v-model:open="modalOpen"
      :title="editing ? '编辑分类' : '新建分类'"
      :width="isMobile ? '100%' : '600px'"
      :style="isMobile ? { top: 0, paddingBottom: 0 } : {}"
      :bodyStyle="isMobile ? { maxHeight: 'calc(100vh - 110px)', overflow: 'auto' } : {}"
      @ok="handleSubmit"
      :confirmLoading="saving"
    >
      <a-form :model="form" layout="vertical">
        <a-form-item label="名称" required>
          <a-input v-model:value="form.name" />
        </a-form-item>
        <a-form-item label="Key" required>
          <a-input v-model:value="form.key" />
        </a-form-item>
        <a-form-item label="排序">
          <a-input-number v-model:value="form.order" :min="0" style="width: 100%" />
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
// @ts-ignore Nuxt auto-import
definePageMeta({
  ssr: false, // 禁用 SSR，避免 Ant Design Vue 组件在服务端渲染时出错
});

import { ref, reactive, onMounted } from "vue";
import { message } from "ant-design-vue";
import { useApiFetch } from "../composables/useApiFetch";
import { useMobile } from "../composables/useMobile";

const { isMobile } = useMobile();

// @ts-ignore Nuxt auto-import
useHead({
  title: "分类管理 - 天赐印记后台",
});

interface Category {
  id: number;
  name: string;
  key: string;
  order: number;
  createdAt: string;
  updatedAt: string;
}

interface CategoryForm {
  name: string;
  key: string;
  order: number;
}

const $api = useApiFetch();
const loading = ref(false);
const saving = ref(false);
const categories = ref<Category[]>([]);

const columns = [
  { title: "ID", dataIndex: "id", key: "id", width: 60 },
  { title: "名称", dataIndex: "name", key: "name" },
  { title: "Key", dataIndex: "key", key: "key" },
  { title: "排序", dataIndex: "order", key: "order", width: 80 },
  {
    title: "操作",
    key: "actions",
    width: 160,
  },
];

const emptyForm = (): CategoryForm => ({
  name: "",
  key: "",
  order: 0,
});

const form = reactive<CategoryForm>(emptyForm());
const modalOpen = ref(false);
const editing = ref(false);
const editingId = ref<number | null>(null);

const fetchCategories = async () => {
  try {
    loading.value = true;
    const res = await $api<{
      statusCode: number;
      data?: Category[];
      error?: string;
    }>("/api/categories");

    if (res.statusCode === 200 && res.data) {
      categories.value = res.data;
    } else {
      message.error(res.error || "获取分类列表失败");
    }
  } catch (error: any) {
    message.error(error?.data?.error || "获取分类列表失败");
  } finally {
    loading.value = false;
  }
};

const resetForm = () => {
  Object.assign(form, emptyForm());
};

const openCreate = () => {
  editing.value = false;
  editingId.value = null;
  resetForm();
  modalOpen.value = true;
};

const openEdit = (record: Category) => {
  editing.value = true;
  editingId.value = record.id;
  Object.assign(form, {
    name: record.name,
    key: record.key,
    order: record.order,
  });
  modalOpen.value = true;
};

const handleSubmit = async () => {
  if (!form.name || !form.key) {
    message.warning("名称和 key 为必填项");
    return;
  }

  const payload = { ...form };

  try {
    saving.value = true;
    if (editing.value && editingId.value != null) {
      const res = await $api<{
        statusCode: number;
        data?: Category;
        error?: string;
      }>(`/api/categories/${editingId.value}`, {
        method: "PUT",
        body: payload,
      });
      if (res.statusCode === 200 && res.data) {
        message.success("更新成功");
        modalOpen.value = false;
        fetchCategories();
      } else {
        message.error(res.error || "更新失败");
      }
    } else {
      const res = await $api<{
        statusCode: number;
        data?: Category;
        error?: string;
      }>("/api/categories", {
        method: "POST",
        body: payload,
      });
      if (res.statusCode === 200 && res.data) {
        message.success("创建成功");
        modalOpen.value = false;
        fetchCategories();
      } else {
        message.error(res.error || "创建失败");
      }
    }
  } catch (error: any) {
    message.error(error?.data?.error || "保存失败");
  } finally {
    saving.value = false;
  }
};

const handleDelete = async (id: number) => {
  try {
    const res = await $api<{
      statusCode: number;
      message?: string;
      error?: string;
    }>(`/api/categories/${id}`, {
      method: "DELETE",
    });
    if (res.statusCode === 200 && res.message && !res.error) {
      message.success(res.message);
      fetchCategories();
    } else {
      message.error(res.error || res.message || "删除失败");
    }
  } catch (error: any) {
    message.error(error?.data?.error || error?.data?.message || "删除失败");
  }
};

onMounted(() => {
  fetchCategories();
});
</script>

<style scoped>
.page-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
  flex-wrap: wrap;
  gap: 12px;
}

/* 移动端优化 */
@media (max-width: 768px) {
  .page-header {
    flex-direction: column;
    align-items: flex-start;
  }

  .page-header h2 {
    font-size: 18px;
    margin: 0;
  }

  /* 表格横向滚动 */
  :deep(.ant-table-wrapper) {
    overflow-x: auto;
  }

  :deep(.ant-table) {
    min-width: 600px;
  }

  :deep(.ant-table-thead > tr > th),
  :deep(.ant-table-tbody > tr > td) {
    padding: 8px 4px;
    font-size: 12px;
  }

  :deep(.ant-space) {
    flex-wrap: wrap;
  }
}
</style>

// tianciyinji_nextjs/src/app/admin/(dashboard)/categories/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import { Button, Form, Input, InputNumber, Modal, Popconfirm, Space, Table, message } from "antd";
import type { ColumnsType } from "antd/es/table";
import { adminFetch } from "@/lib/admin-fetch";

interface Row {
  id: number;
  name: string;
  key: string;
  order: number;
}

export default function CategoriesPage() {
  const [rows, setRows] = useState<Row[]>([]);
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Row | null>(null);
  const [form] = Form.useForm();

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await adminFetch<{ statusCode: number; data?: Row[] }>(
        "/api/categories",
      );
      if (Array.isArray(res.data)) setRows(res.data);
    } catch {
      /* */
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const submit = async () => {
    const v = await form.validateFields();
    try {
      if (editing) {
        await adminFetch(`/api/categories/${editing.id}`, {
          method: "PUT",
          body: JSON.stringify(v),
        });
        message.success("已更新");
      } else {
        await adminFetch("/api/categories", {
          method: "POST",
          body: JSON.stringify(v),
        });
        message.success("已创建");
      }
      setOpen(false);
      load();
    } catch {
      message.error("保存失败");
    }
  };

  const columns: ColumnsType<Row> = [
    { title: "ID", dataIndex: "id", width: 70 },
    { title: "名称", dataIndex: "name" },
    { title: "Key", dataIndex: "key" },
    { title: "排序", dataIndex: "order", width: 80 },
    {
      title: "操作",
      key: "a",
      width: 160,
      render: (_, r) => (
        <Space>
          <Button
            type="link"
            size="small"
            onClick={() => {
              setEditing(r);
              form.setFieldsValue(r);
              setOpen(true);
            }}
          >
            编辑
          </Button>
          <Popconfirm title="确定删除？" onConfirm={async () => {
            await adminFetch(`/api/categories/${r.id}`, { method: "DELETE" });
            message.success("已删除");
            load();
          }}>
            <Button type="link" danger size="small">删除</Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16 }}>
        <h2 style={{ margin: 0 }}>分类管理</h2>
        <Button
          type="primary"
          onClick={() => {
            setEditing(null);
            form.resetFields();
            form.setFieldsValue({ order: 0 });
            setOpen(true);
          }}
        >
          新建
        </Button>
      </div>
      <Table rowKey="id" loading={loading} columns={columns} dataSource={rows} />
      <Modal
        title={editing ? "编辑分类" : "新建分类"}
        open={open}
        onCancel={() => setOpen(false)}
        onOk={submit}
        destroyOnClose
      >
        <Form form={form} layout="vertical">
          <Form.Item name="name" label="名称" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="key" label="Key" rules={[{ required: true }]}>
            <Input disabled={!!editing} />
          </Form.Item>
          <Form.Item name="order" label="排序">
            <InputNumber min={0} style={{ width: "100%" }} />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
