// tianciyinji-admin-backend-master/pages/tags.vue
<template>
  <div>
    <div class="page-header">
      <h2>标签管理</h2>
      <a-button type="primary" @click="openCreate">新建标签</a-button>
    </div>

    <a-table
      :dataSource="tags"
      :columns="columns"
      :loading="loading"
      :pagination="pagination"
      rowKey="id"
      @change="handleTableChange"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'isVisible'">
          <a-tag :color="record.isVisible ? 'green' : 'red'">
            {{ record.isVisible ? "显示" : "隐藏" }}
          </a-tag>
        </template>
        <template v-else-if="column.key === 'actions'">
          <a-space>
            <a-button type="link" @click="openEdit(record)">编辑</a-button>
            <a-popconfirm
              title="确定删除该标签？"
              ok-text="是"
              cancel-text="否"
              @confirm="() => handleDelete(record.id)"
            >
              <a-button type="link" danger>删除</a-button>
            </a-popconfirm>
          </a-space>
        </template>
      </template>
    </a-table>

    <a-modal
      v-model:open="modalOpen"
      :title="editing ? '编辑标签' : '新建标签'"
      :width="isMobile ? '100%' : '600px'"
      :style="isMobile ? { top: 0, paddingBottom: 0 } : {}"
      :bodyStyle="isMobile ? { maxHeight: 'calc(100vh - 110px)', overflow: 'auto' } : {}"
      @ok="handleSubmit"
      :confirmLoading="saving"
    >
      <a-form :model="form" layout="vertical">
        <a-form-item label="标题" required>
          <a-input v-model:value="form.title" />
        </a-form-item>
        <a-form-item label="Key" required>
          <a-input v-model:value="form.key" />
        </a-form-item>
        <a-form-item label="排序">
          <a-input-number v-model:value="form.order" :min="0" style="width: 100%" />
        </a-form-item>
        <a-form-item label="是否显示">
          <a-switch v-model:checked="form.isVisible" />
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
// @ts-ignore Nuxt auto-import
definePageMeta({
  ssr: false, // 禁用 SSR，避免 Ant Design Vue 组件在服务端渲染时出错
});

import { ref, reactive, onMounted } from "vue";
import { message } from "ant-design-vue";
import { useApiFetch } from "../composables/useApiFetch";
import { useMobile } from "../composables/useMobile";

const { isMobile } = useMobile();

// @ts-ignore Nuxt auto-import
useHead({
  title: "标签管理 - 天赐印记后台",
});

interface Tag {
  id: number;
  title: string;
  key: string;
  order: number;
  isVisible: boolean;
  createdAt: string;
  updatedAt: string;
}

interface TagForm {
  title: string;
  key: string;
  order: number;
  isVisible: boolean;
}

const loading = ref(false);
const saving = ref(false);
const tags = ref<Tag[]>([]);

const pagination = reactive({
  current: 1,
  pageSize: 10,
  total: 0,
  showSizeChanger: true,
  showTotal: (total: number) => `共 ${total} 条`,
});

const columns = [
  { title: "ID", dataIndex: "id", key: "id", width: 60 },
  { title: "标题", dataIndex: "title", key: "title" },
  { title: "Key", dataIndex: "key", key: "key" },
  { title: "排序", dataIndex: "order", key: "order", width: 80 },
  { title: "显示", dataIndex: "isVisible", key: "isVisible", width: 80 },
  {
    title: "操作",
    key: "actions",
    width: 160,
  },
];

const emptyForm = (): TagForm => ({
  title: "",
  key: "",
  order: 0,
  isVisible: true,
});

const form = reactive<TagForm>(emptyForm());
const modalOpen = ref(false);
const editing = ref(false);
const editingId = ref<number | null>(null);

const $api = useApiFetch();

const fetchTags = async () => {
  try {
    loading.value = true;
    const res = await $api<{
      statusCode: number;
      data?: {
        data: Tag[];
        pagination: {
          current: number;
          pageSize: number;
          total: number;
          totalPages: number;
        };
      };
      error?: string;
    }>("/api/tags", {
      query: {
        page: pagination.current,
        pageSize: pagination.pageSize,
      },
    });

    if (res.statusCode === 200 && res.data) {
      tags.value = res.data.data;
      pagination.total = res.data.pagination.total;
      pagination.current = res.data.pagination.current;
      pagination.pageSize = res.data.pagination.pageSize;
    } else {
      message.error(res.error || "获取标签列表失败");
    }
  } catch (error: any) {
    message.error(error?.data?.error || "获取标签列表失败");
  } finally {
    loading.value = false;
  }
};

const handleTableChange = (pag: any) => {
  pagination.current = pag.current;
  pagination.pageSize = pag.pageSize;
  fetchTags();
};

const resetForm = () => {
  Object.assign(form, emptyForm());
};

const openCreate = () => {
  editing.value = false;
  editingId.value = null;
  resetForm();
  modalOpen.value = true;
};

const openEdit = (record: Tag) => {
  editing.value = true;
  editingId.value = record.id;
  Object.assign(form, {
    title: record.title,
    key: record.key,
    order: record.order,
    isVisible: record.isVisible,
  });
  modalOpen.value = true;
};

const handleSubmit = async () => {
  if (!form.title || !form.key) {
    message.warning("标题和 key 为必填项");
    return;
  }

  const payload = { ...form };

  try {
    saving.value = true;
    if (editing.value && editingId.value != null) {
      const res = await $api<{
        statusCode: number;
        data?: Tag;
        error?: string;
      }>(`/api/tags/${editingId.value}`, {
        method: "PUT",
        body: payload,
      });
      if (res.statusCode === 200 && res.data) {
        message.success("更新成功");
        modalOpen.value = false;
        fetchTags();
      } else {
        message.error(res.error || "更新失败");
      }
    } else {
      const res = await $api<{
        statusCode: number;
        data?: Tag;
        error?: string;
      }>("/api/tags", {
        method: "POST",
        body: payload,
      });
      if (res.statusCode === 200 && res.data) {
        message.success("创建成功");
        modalOpen.value = false;
        fetchTags();
      } else {
        message.error(res.error || "创建失败");
      }
    }
  } catch (error: any) {
    message.error(error?.data?.error || "保存失败");
  } finally {
    saving.value = false;
  }
};

const handleDelete = async (id: number) => {
  try {
    const res = await $api<{
      statusCode: number;
      message?: string;
      error?: string;
    }>(`/api/tags/${id}`, {
      method: "DELETE",
    });
    if (res.statusCode === 200 && res.message && !res.error) {
      message.success(res.message);
      fetchTags();
    } else {
      message.error(res.error || res.message || "删除失败");
    }
  } catch (error: any) {
    message.error(error?.data?.error || error?.data?.message || "删除失败");
  }
};

onMounted(() => {
  fetchTags();
});
</script>

<style scoped>
.page-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
  flex-wrap: wrap;
  gap: 12px;
}

/* 移动端优化 */
@media (max-width: 768px) {
  .page-header {
    flex-direction: column;
    align-items: flex-start;
  }

  .page-header h2 {
    font-size: 18px;
    margin: 0;
  }

  :deep(.ant-table-wrapper) {
    overflow-x: auto;
  }

  :deep(.ant-table) {
    min-width: 600px;
  }

  :deep(.ant-table-thead > tr > th),
  :deep(.ant-table-tbody > tr > td) {
    padding: 8px 4px;
    font-size: 12px;
  }

  :deep(.ant-space) {
    flex-wrap: wrap;
  }
}
</style>

// tianciyinji_nextjs/src/app/admin/(dashboard)/tags/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import {
  Button,
  Form,
  Input,
  InputNumber,
  Modal,
  Popconfirm,
  Space,
  Switch,
  Table,
  message,
} from "antd";
import type { ColumnsType } from "antd/es/table";
import { adminFetch } from "@/lib/admin-fetch";

interface Row {
  id: number;
  title: string;
  key: string;
  order: number;
  isVisible: boolean;
}

export default function TagsPage() {
  const [rows, setRows] = useState<Row[]>([]);
  const [loading, setLoading] = useState(false);
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const pageSize = 20;
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Row | null>(null);
  const [form] = Form.useForm();

  const load = useCallback(async (p: number) => {
    setLoading(true);
    try {
      const res = await adminFetch<{
        statusCode: number;
        data?: { data: Row[]; pagination: { total: number } };
      }>(`/api/tags?page=${p}&pageSize=${pageSize}`);
      if (res.data) {
        setRows(res.data.data ?? []);
        setTotal(res.data.pagination?.total ?? 0);
      }
    } catch {
      /* */
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load(page);
  }, [load, page]);

  const submit = async () => {
    const v = await form.validateFields();
    try {
      if (editing) {
        await adminFetch(`/api/tags/${editing.id}`, {
          method: "PUT",
          body: JSON.stringify(v),
        });
        message.success("已更新");
      } else {
        await adminFetch("/api/tags", {
          method: "POST",
          body: JSON.stringify({ ...v, isVisible: v.isVisible ?? true }),
        });
        message.success("已创建");
      }
      setOpen(false);
      load(page);
    } catch {
      message.error("保存失败");
    }
  };

  const columns: ColumnsType<Row> = [
    { title: "ID", dataIndex: "id", width: 70 },
    { title: "标题", dataIndex: "title" },
    { title: "Key", dataIndex: "key" },
    { title: "排序", dataIndex: "order", width: 80 },
    {
      title: "可见",
      dataIndex: "isVisible",
      width: 80,
      render: (v: boolean) => (v ? "是" : "否"),
    },
    {
      title: "操作",
      key: "a",
      width: 160,
      render: (_, r) => (
        <Space>
          <Button
            type="link"
            size="small"
            onClick={() => {
              setEditing(r);
              form.setFieldsValue(r);
              setOpen(true);
            }}
          >
            编辑
          </Button>
          <Popconfirm
            title="确定删除？"
            onConfirm={async () => {
              await adminFetch(`/api/tags/${r.id}`, { method: "DELETE" });
              message.success("已删除");
              load(page);
            }}
          >
            <Button type="link" danger size="small">
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          marginBottom: 16,
        }}
      >
        <h2 style={{ margin: 0 }}>标签管理</h2>
        <Button
          type="primary"
          onClick={() => {
            setEditing(null);
            form.resetFields();
            form.setFieldsValue({ order: 0, isVisible: true });
            setOpen(true);
          }}
        >
          新建
        </Button>
      </div>
      <Table
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={rows}
        pagination={{
          current: page,
          pageSize,
          total,
          onChange: setPage,
        }}
      />
      <Modal
        title={editing ? "编辑标签" : "新建标签"}
        open={open}
        onCancel={() => setOpen(false)}
        onOk={submit}
        destroyOnClose
      >
        <Form form={form} layout="vertical">
          <Form.Item name="title" label="标题" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="key" label="Key" rules={[{ required: true }]}>
            <Input disabled={!!editing} />
          </Form.Item>
          <Form.Item name="order" label="排序">
            <InputNumber min={0} style={{ width: "100%" }} />
          </Form.Item>
          <Form.Item name="isVisible" label="可见" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
